### ISSUE TITLE
Logging in you app

### ISSUE THREAD

**Issue by air133** [antze-k/ao-killboard-py#1]
Hello. Could you add the logging of your program?
According to her actions, for example, polling a kilboard, sending a message to a bot, etc. That it would be possible to correctly track its work. Thank you very much.

**Comment by antze-k** [comment]
Hello.

Sure, I'll add the option of verbose logging in a while.

**Comment by air133** [comment]
Great job! i am on debug mode.
for 1 day of testing, 1 kill did not get into the bot, although it is on the site on my guild. Now we will observe and I can provide you with feedback. Thank you for your project.

**Comment by antze-k** [comment]
Finalized and tested in v0.1.2. Thank you for your feedback.

Unfortunately the Albion Online API is often unreachable, that's how the kills avoid being tracked -- you can see this during "read timeout" messages in the debug log. I see no stable way to fix this, only some ideas which wouldn't guarantee anything, due to the way the API works.
